from time import sleep

from selenium.webdriver import  Chrome, ChromeOptions
from selenium.webdriver.common.by import By

o=ChromeOptions()
o.add_experimental_option('detach',True)
driver=Chrome(options=o)
driver.get("https://demowebshop.tricentis.com/")
driver.maximize_window()
driver.find_element(By.CLASS_NAME,'ico-register').click()
sleep(2)
driver.find_element(By.ID,'gender-male').click()
sleep(2)
driver.find_element(By.ID,'FirstName').send_keys('Rahul')
sleep(2)
driver.find_element(By.ID,'LastName').send_keys('Kumar')
sleep(2)
driver.find_element(By.ID,'Email').send_keys('rk5700177@gmail.com')
sleep(2)
driver.find_element(By.CLASS_NAME,'text-box.single-line.password').send_keys('R@hulku133')
sleep(2)
driver.find_element(By.ID,'ConfirmPassword').send_keys('R@hulku133')
sleep(2)
driver.find_element(By.ID,'register-button').click()
sleep(2)
driver.find_element(By.CLASS_NAME,'ico-login').click()
sleep(2)
driver.find_element(By.ID,'Email').send_keys('rk5700177@gmail.com')
sleep(2)
driver.find_element(By.ID,'Password').send_keys('R@hulku133')
sleep(2)
driver.find_element(By.ID,'RememberMe').click()
sleep(2)
driver.find_element(By.CLASS_NAME,'button-1.login-button').click()
sleep(2)
print(driver.title)
sleep(5)
