from time import sleep

from selenium.webdriver import  Chrome, ChromeOptions
from selenium.webdriver.common.by import By

o=ChromeOptions()
o.add_experimental_option('detach',True)
driver=Chrome(options=o)
driver.get("https://open.spotify.com/")
driver.maximize_window()
sleep(2)
driver.find_element(By.XPATH,'//button[@data-testid="signup-button"]').click()
sleep(2)
driver.find_element(By.XPATH,'//input[@type="email"]').send_keys('rk5700177@gmail.com')
sleep(2)
driver.find_element(By.CLASS_NAME,"e-91031-baseline.e-91031-overflow-wrap-anywhere.e-91031-button-primary__inner.encore-bright-accent-set.e-91031-button--medium").click()
sleep(2)
driver.find_element(By.XPATH,'//input[@id="new-password"]').send_keys('rahulk133@')
sleep(2)
driver.find_element(By.XPATH,'//span[.="Next"]').click()
sleep(2)
driver.find_element(By.XPATH,'//input[@id="displayName"]').send_keys('Rahul kumar')
sleep(2)
driver.find_element(By.XPATH,'//input[@id="year"]').send_keys('2003')
sleep(2)
driver.find_element(By.XPATH,'//input[@id="day"]').send_keys('06')
sleep(10)
driver.find_element(By.XPATH,'(//span[@class="Indicator-sc-hjfusp-0 foJdWc"])[1]').click()
sleep(2)
driver.find_element(By.XPATH,'//span[.="Next"]').click()
sleep(2)
driver.find_element(By.XPATH,'(//span[@class="Indicator-sc-1airx73-0 bJVFXo"])[1]').click()
sleep(2)
driver.find_element(By.XPATH,'(//span[@class="Indicator-sc-1airx73-0 bJVFXo"])[2]').click()
sleep(2)
driver.find_element(By.XPATH,'//span[.="Sign up"]').click()
sleep(2)
